import {
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptNotAvailableLanguageError,
  YoutubeTranscriptVideoUnavailableError,
  fetchTranscript,
  type TranscriptResponse,
} from 'youtube-transcript';

import { readEnv } from '@/lib/env';

const YOUTUBE_API_BASE_URL = 'https://www.googleapis.com/youtube/v3';
const REQUEST_TIMEOUT_MS = 5_000;
const CAPTION_LANGUAGE_PREFERENCES = ['ko', 'ko-KR', 'en', 'en-US'];

type FetchLike = typeof fetch;
type FetchTranscriptLike = typeof fetchTranscript;

interface ApiErrorPayload {
  error?: {
    code?: number;
    message?: string;
    errors?: Array<{
      reason?: string;
    }>;
  };
}

interface VideoThumbnails {
  maxres?: { url?: string };
  high?: { url?: string };
  medium?: { url?: string };
  standard?: { url?: string };
  default?: { url?: string };
}

interface YouTubeVideoListResponse extends ApiErrorPayload {
  items?: Array<{
    snippet?: {
      title?: string;
      description?: string;
      channelTitle?: string;
      defaultLanguage?: string;
      defaultAudioLanguage?: string;
      thumbnails?: VideoThumbnails;
    };
    contentDetails?: {
      duration?: string;
    };
  }>;
}

interface YouTubeCaptionsListResponse extends ApiErrorPayload {
  items?: Array<{
    snippet?: {
      language?: string;
      trackKind?: string;
      isAutoSynced?: boolean;
    };
  }>;
}

interface CaptionTrack {
  language: string;
  isAutoGenerated: boolean;
  isAutoSynced: boolean;
}

interface ApiClientOptions {
  fetchImpl?: FetchLike;
  fetchTranscriptImpl?: FetchTranscriptLike;
}

export interface VideoMetadata {
  title: string;
  description: string;
  thumbnailUrl: string;
  channelName: string;
  language: string | null;
  durationSeconds: number | null;
}

export interface CaptionResult {
  text: string;
  language: string | null;
  isAutoGenerated: boolean;
}

export class YouTubeApiError extends Error {
  constructor(
    public readonly code:
      | 'QUOTA_EXCEEDED'
      | 'VIDEO_NOT_FOUND'
      | 'METADATA_FETCH_FAILED'
      | 'CAPTIONS_FETCH_FAILED',
    message: string,
  ) {
    super(message);
    this.name = 'YouTubeApiError';
  }
}

function createTimeoutSignal(timeoutMs: number) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

  return {
    signal: controller.signal,
    cleanup: () => clearTimeout(timeoutId),
  };
}

function isAbortError(error: unknown) {
  return error instanceof Error && error.name === 'AbortError';
}

function isQuotaError(payload: ApiErrorPayload | null | undefined) {
  return payload?.error?.errors?.some((error) =>
    ['quotaExceeded', 'dailyLimitExceeded', 'rateLimitExceeded'].includes(
      error.reason ?? '',
    ),
  );
}

function parseDurationToSeconds(duration: string | undefined) {
  if (!duration) {
    return null;
  }

  const match = duration.match(
    /^P(?:\d+Y)?(?:\d+M)?(?:\d+D)?T?(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/,
  );

  if (!match) {
    return null;
  }

  const [, hours = '0', minutes = '0', seconds = '0'] = match;

  return (
    Number.parseInt(hours, 10) * 3600 +
    Number.parseInt(minutes, 10) * 60 +
    Number.parseInt(seconds, 10)
  );
}

function getPreferredThumbnailUrl(thumbnails: VideoThumbnails | undefined) {
  return (
    thumbnails?.maxres?.url ??
    thumbnails?.high?.url ??
    thumbnails?.standard?.url ??
    thumbnails?.medium?.url ??
    thumbnails?.default?.url ??
    ''
  );
}

async function fetchJson<T extends ApiErrorPayload>(
  url: string,
  options: RequestInit = {},
  retries = 1,
  fetchImpl: FetchLike = fetch,
): Promise<T> {
  const { signal, cleanup } = createTimeoutSignal(REQUEST_TIMEOUT_MS);

  try {
    const response = await fetchImpl(url, {
      ...options,
      signal,
    });
    const payload = (await response.json()) as T;

    if (!response.ok) {
      if (response.status === 403 && isQuotaError(payload)) {
        throw new YouTubeApiError(
          'QUOTA_EXCEEDED',
          'YouTube API quota exceeded. Please try again later.',
        );
      }

      if (response.status === 404) {
        throw new YouTubeApiError(
          'VIDEO_NOT_FOUND',
          'The requested YouTube video could not be found.',
        );
      }

      throw Object.assign(
        new Error(payload.error?.message ?? 'Request failed.'),
        {
          responseStatus: response.status,
          payload,
        },
      );
    }

    return payload;
  } catch (error) {
    if (retries > 0 && (isAbortError(error) || error instanceof TypeError)) {
      return fetchJson(url, options, retries - 1, fetchImpl);
    }

    throw error;
  } finally {
    cleanup();
  }
}

function sortCaptionTracks(tracks: CaptionTrack[]) {
  return [...tracks].sort((left, right) => {
    if (left.isAutoGenerated !== right.isAutoGenerated) {
      return left.isAutoGenerated ? 1 : -1;
    }

    const leftLanguageScore =
      CAPTION_LANGUAGE_PREFERENCES.indexOf(left.language) === -1
        ? Number.MAX_SAFE_INTEGER
        : CAPTION_LANGUAGE_PREFERENCES.indexOf(left.language);
    const rightLanguageScore =
      CAPTION_LANGUAGE_PREFERENCES.indexOf(right.language) === -1
        ? Number.MAX_SAFE_INTEGER
        : CAPTION_LANGUAGE_PREFERENCES.indexOf(right.language);

    return leftLanguageScore - rightLanguageScore;
  });
}

function compactTranscript(entries: TranscriptResponse[]) {
  return entries
    .map((entry) => entry.text.trim())
    .filter(Boolean)
    .join('\n');
}

function extractTranscriptLanguage(entries: TranscriptResponse[]) {
  return entries.find((entry) => entry.lang)?.lang ?? null;
}

function buildTranscriptLanguageAttempts(tracks: CaptionTrack[]) {
  const rankedTrackLanguages = sortCaptionTracks(tracks).map(
    (track) => track.language,
  );

  return [
    ...new Set([...rankedTrackLanguages, ...CAPTION_LANGUAGE_PREFERENCES]),
  ];
}

async function fetchCaptionTracks(
  videoId: string,
  fetchImpl: FetchLike = fetch,
) {
  const env = readEnv();
  const params = new URLSearchParams({
    part: 'snippet',
    videoId,
    key: env.YOUTUBE_API_KEY,
  });
  const payload = await fetchJson<YouTubeCaptionsListResponse>(
    `${YOUTUBE_API_BASE_URL}/captions?${params.toString()}`,
    undefined,
    1,
    fetchImpl,
  );

  return (
    payload.items
      ?.map((item) => item.snippet)
      .filter((snippet): snippet is NonNullable<typeof snippet> =>
        Boolean(snippet?.language),
      )
      .map((snippet) => ({
        language: snippet.language!,
        isAutoGenerated: snippet.trackKind === 'ASR',
        isAutoSynced: Boolean(snippet.isAutoSynced),
      })) ?? []
  );
}

function isTranscriptUnavailableError(error: unknown) {
  return (
    error instanceof YoutubeTranscriptDisabledError ||
    error instanceof YoutubeTranscriptNotAvailableError ||
    error instanceof YoutubeTranscriptNotAvailableLanguageError
  );
}

export async function fetchVideoMetadata(
  videoId: string,
  options: ApiClientOptions = {},
): Promise<VideoMetadata> {
  const env = readEnv();
  const params = new URLSearchParams({
    part: 'snippet,contentDetails',
    id: videoId,
    key: env.YOUTUBE_API_KEY,
  });

  try {
    const payload = await fetchJson<YouTubeVideoListResponse>(
      `${YOUTUBE_API_BASE_URL}/videos?${params.toString()}`,
      undefined,
      1,
      options.fetchImpl,
    );
    const item = payload.items?.[0];

    if (!item?.snippet) {
      throw new YouTubeApiError(
        'VIDEO_NOT_FOUND',
        'The requested YouTube video could not be found.',
      );
    }

    return {
      title: item.snippet.title ?? '',
      description: item.snippet.description ?? '',
      thumbnailUrl: getPreferredThumbnailUrl(item.snippet.thumbnails),
      channelName: item.snippet.channelTitle ?? '',
      language:
        item.snippet.defaultLanguage ??
        item.snippet.defaultAudioLanguage ??
        null,
      durationSeconds: parseDurationToSeconds(item.contentDetails?.duration),
    };
  } catch (error) {
    if (error instanceof YouTubeApiError) {
      throw error;
    }

    throw new YouTubeApiError(
      'METADATA_FETCH_FAILED',
      'Failed to fetch YouTube video metadata.',
    );
  }
}

export async function fetchCaptions(
  videoId: string,
  options: ApiClientOptions = {},
): Promise<CaptionResult | null> {
  let tracks: CaptionTrack[] = [];

  try {
    tracks = await fetchCaptionTracks(videoId, options.fetchImpl);
  } catch (error) {
    if (error instanceof YouTubeApiError) {
      if (error.code === 'QUOTA_EXCEEDED' || error.code === 'VIDEO_NOT_FOUND') {
        throw error;
      }
    }
  }

  const attempts = buildTranscriptLanguageAttempts(tracks);

  for (const language of attempts) {
    try {
      const transcript = await (options.fetchTranscriptImpl ?? fetchTranscript)(
        videoId,
        {
          lang: language,
          fetch: options.fetchImpl,
        },
      );
      const track = sortCaptionTracks(tracks).find(
        (candidate) => candidate.language === language,
      );

      return {
        text: compactTranscript(transcript),
        language,
        isAutoGenerated: track?.isAutoGenerated ?? false,
      };
    } catch (error) {
      if (error instanceof YoutubeTranscriptNotAvailableLanguageError) {
        continue;
      }

      if (error instanceof YoutubeTranscriptVideoUnavailableError) {
        throw new YouTubeApiError(
          'VIDEO_NOT_FOUND',
          'The requested YouTube video could not be found.',
        );
      }

      if (isTranscriptUnavailableError(error)) {
        return null;
      }

      throw new YouTubeApiError(
        'CAPTIONS_FETCH_FAILED',
        'Failed to fetch YouTube captions.',
      );
    }
  }

  try {
    const transcript = await (options.fetchTranscriptImpl ?? fetchTranscript)(
      videoId,
      options.fetchImpl ? { fetch: options.fetchImpl } : undefined,
    );
    const preferredTrack = sortCaptionTracks(tracks)[0];

    return {
      text: compactTranscript(transcript),
      language:
        extractTranscriptLanguage(transcript) ??
        preferredTrack?.language ??
        null,
      isAutoGenerated: preferredTrack?.isAutoGenerated ?? false,
    };
  } catch (error) {
    if (error instanceof YoutubeTranscriptVideoUnavailableError) {
      throw new YouTubeApiError(
        'VIDEO_NOT_FOUND',
        'The requested YouTube video could not be found.',
      );
    }

    if (isTranscriptUnavailableError(error)) {
      return null;
    }

    throw new YouTubeApiError(
      'CAPTIONS_FETCH_FAILED',
      'Failed to fetch YouTube captions.',
    );
  }
}
